---
title: "Distribution of Bank Accross Zimbabwe"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(billboarder)
library(dplyr)
library(tidyverse)

setwd("C:\\Users\\Calvin.Ndunduma\\Documents\\Bank distribustion")

bank_data <- read.csv("Bank_Codes.csv")
class(bank_data)
head(bank_data)
bank_data %>% count(Town)

summarized_data <- bank_data %>% group_by(Banks, Town) %>% summarise(Branch = n())
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

ggplot(data = summarized_data) + 
  geom_point(mapping = aes(x = Banks, y = Town))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Banks

```{r}

ban_data <- table(summarized_data$Banks)
billboarder() %>% bb_piechart(ban_data)

```

### Cities

```{r}


tw_data <- table(summarized_data$Town)
billboarder() %>% bb_piechart(tw_data)

```

